// <auto-generated />
using System;
using AiOption.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AiOption.Infrastructure.Migrations
{
    [DbContext(typeof(AiOptionDbContext))]
    [Migration("20181001020813_AddCustomerLevel")]
    partial class AddCustomerLevel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AiOption.Infrastructure.ReadStores.ReadModels.CustomerReadModel", b =>
                {
                    b.Property<string>("AggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountId");

                    b.Property<string>("InvitationCode");

                    b.Property<int?>("Level");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("AggregateId");

                    b.ToTable("CustomerReadModel");
                });

            modelBuilder.Entity("AiOption.Infrastructure.ReadStores.ReadModels.IqAccountReadModel", b =>
                {
                    b.Property<string>("AggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountId");

                    b.Property<string>("CustomerReadModelAggregateId");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("AggregateId");

                    b.HasIndex("CustomerReadModelAggregateId");

                    b.ToTable("IqAccountReadModel");
                });

            modelBuilder.Entity("EventFlow.EntityFramework.EventStores.EventEntity", b =>
                {
                    b.Property<long>("GlobalSequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AggregateId");

                    b.Property<string>("AggregateName");

                    b.Property<int>("AggregateSequenceNumber");

                    b.Property<Guid>("BatchId");

                    b.Property<string>("Data");

                    b.Property<string>("Metadata");

                    b.HasKey("GlobalSequenceNumber");

                    b.HasIndex("AggregateId", "AggregateSequenceNumber")
                        .IsUnique()
                        .HasFilter("[AggregateId] IS NOT NULL");

                    b.ToTable("EventEntity");
                });

            modelBuilder.Entity("EventFlow.EntityFramework.SnapshotStores.SnapshotEntity", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AggregateId");

                    b.Property<string>("AggregateName");

                    b.Property<int>("AggregateSequenceNumber");

                    b.Property<string>("Data");

                    b.Property<string>("Metadata");

                    b.HasKey("AccountId");

                    b.HasIndex("AggregateName", "AggregateId", "AggregateSequenceNumber")
                        .IsUnique()
                        .HasFilter("[AggregateName] IS NOT NULL AND [AggregateId] IS NOT NULL");

                    b.ToTable("SnapshotEntity");
                });

            modelBuilder.Entity("AiOption.Infrastructure.ReadStores.ReadModels.IqAccountReadModel", b =>
                {
                    b.HasOne("AiOption.Infrastructure.ReadStores.ReadModels.CustomerReadModel", "CustomerReadModel")
                        .WithMany("IqAccountReadModels")
                        .HasForeignKey("CustomerReadModelAggregateId");
                });
#pragma warning restore 612, 618
        }
    }
}
