version: '3.5'

services:
  mssql:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "Str0ngPassword!"
        ACCEPT_EULA: "Y"
    networks:
      - api
    ports:
      - 1401:1433
 
networks:  
  api:
    external: true